%include "colon.inc"

section .data

colon "Limbo", limbo
db "First circle of HELL", 0

colon "Lust", lust
db "Second circle of HELL", 0

colon "Gluttony", gluttony
db "Third circle of HELL", 0

colon "Greed", greed
db "Fourth circle of HELL", 0

colon "Wraith", wraith
db "Fifth circle of HELL", 0

colon "Heresy", heresy
db "Sixth circle of HELL", 0

colon "Violence", violence
db "Seventh circle of HELL", 0

colon "Fraud", fraud
db "Eighth circle of HELL", 0

colon "Treachery", treachery
db "Ninth circle of HELL", 0